### ISSUE TITLE
Gondola "platform" Solid

### ISSUE THREAD

**Issue by marina-go-al** [newdexterity/Airship#1]
Hello! I am interested in 3d printing the gondola for an educational project using a blimp. However, I have noticed that the "platform" assembly only contains the bottom propeller module and not the ones on the sides (and their corresponding parts/holes), as it appears in the paper. Therefore, I was wondering: could there be something that I am missing?
Thank you very much in advance! (:

**Comment by ggorjup** [comment]
Hello, thank you for spotting this - some parts were indeed missing. 
I've updated the CAD files so everything should be included now: e76559c849d5d8f82b12d201c0d6f98a5627f370

**Comment by marina-go-al** [comment]
Perfect, thank you very much, I really appreciate it! Everything looks awesome now

**Comment by ggorjup** [comment]
Great!
